repos:
- repo: local
  hooks:
    - id: llmkg-backend-lint-pytest
      name: Run LLMKG Backend python lint and pytest
      entry: bash -c 'cd src && make test'
      language: system
      pass_filenames: false
