services:
  app:
    build:
      context: ./src
      target: development
    volumes:
      - ./src:/app
    depends_on:
      neo4j:
        condition: service_started
    environment:
      DEBUG: "true"
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
    ports:
      - "8000:8000"
    command: >
      CompileDaemon
        -color=true
        -build="make compile-binaries"
        -command="build/app"
        -exclude-dir=.git
        -exclude-dir=./build
        -exclude-dir=./internal/openapi/ogen
        -include=openapi-schema.yaml
        -include=go.mod
        -include=go.sum

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  neo4j_data:
